services:
  innoaggie:
    image: innoaggie:latest
    build: . 
    container_name: innoaggie
    ports:
      - "3000:3000"
    restart: unless-stopped
    

  nginx:
    image: nginx:alpine
    container_name: innoaggie_nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # serve ACME challenges from a shared host dir
      - /var/www/certbot:/var/www/certbot
      # mount LE certs read-only
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - innoaggie

networks:
  default:
    external:
      name: innoaggie-net