services:
  innoaggie:
    image: innoaggie:latest
    build: . 
    container_name: innoaggie
    ports:
      - "3000:3000"
    restart: unless-stopped
    

  nginx:
    image: nginx:alpine
    container_name: innoaggie_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - innoaggie

networks:
  default:
    driver: bridge